namespace Pangram.Sdk.Tests;

public sealed class PredictAsyncTests
{
    private const string ValidResponse = """
                                         {
                                             "text": "The quick brown fox",
                                             "version": "3.0",
                                             "headline": "Likely AI-Generated",
                                             "prediction": "This text was likely generated by an AI model.",
                                             "prediction_short": "AI",
                                             "fraction_ai": 0.85,
                                             "fraction_ai_assisted": 0.10,
                                             "fraction_human": 0.05,
                                             "num_ai_segments": 3,
                                             "num_ai_assisted_segments": 1,
                                             "num_human_segments": 0,
                                             "windows": [
                                                 {
                                                     "text": "The quick brown fox",
                                                     "label": "AI-Generated",
                                                     "ai_assistance_score": 0.91,
                                                     "confidence": "High",
                                                     "start_index": 0,
                                                     "end_index": 19,
                                                     "word_count": 4,
                                                     "token_length": 5
                                                 }
                                             ]
                                         }
                                         """;

    [Fact]
    public async Task PredictAsync_ValidText_ReturnsMappedResponse()
    {
        using var client = ClientFactory.Create(ValidResponse);

        var result = await client.PredictAsync("The quick brown fox", cancellationToken: TestContext.Current.CancellationToken);

        Assert.Equal("The quick brown fox", result.Text);
        Assert.Equal("3.0", result.Version);
        Assert.Equal("AI", result.PredictionShort);
        Assert.Equal(0.85f, result.FractionAi, precision: 2);
        Assert.Equal(0.10f, result.FractionAiAssisted, precision: 2);
        Assert.Equal(0.05f, result.FractionHuman, precision: 2);
        Assert.Equal(3, result.NumAiSegments);
        Assert.Equal(1, result.NumAiAssistedSegments);
        Assert.Equal(0, result.NumHumanSegments);
        Assert.Null(result.DashboardLink);
    }

    [Fact]
    public async Task PredictAsync_Windows_AreMapped()
    {
        using var client = ClientFactory.Create(ValidResponse);

        var result = await client.PredictAsync("The quick brown fox", cancellationToken: TestContext.Current.CancellationToken);

        Assert.Single(result.Windows);
        var w = result.Windows[0];
        Assert.Equal("The quick brown fox", w.Text);
        Assert.Equal("AI-Generated", w.Label);
        Assert.Equal(0.91f, w.AiAssistanceScore, precision: 2);
        Assert.Equal("High", w.Confidence);
        Assert.Equal(0, w.StartIndex);
        Assert.Equal(19, w.EndIndex);
        Assert.Equal(4, w.WordCount);
        Assert.Equal(5, w.TokenLength);
    }

    [Fact]
    public async Task PredictAsync_WithDashboardLink_ResponseContainsLink()
    {
        const string responseWithLink = """
                                        {
                                            "text": "Hello",
                                            "version": "3.0",
                                            "headline": "Human",
                                            "prediction": "Human written",
                                            "prediction_short": "Human",
                                            "fraction_ai": 0.0,
                                            "fraction_ai_assisted": 0.0,
                                            "fraction_human": 1.0,
                                            "num_ai_segments": 0,
                                            "num_ai_assisted_segments": 0,
                                            "num_human_segments": 1,
                                            "dashboard_link": "https://dashboard.pangram.com/result/abc123",
                                            "windows": []
                                        }
                                        """;

        using var client = ClientFactory.Create(responseWithLink);

        var result = await client.PredictAsync("Hello", publicDashboardLink: true, cancellationToken: TestContext.Current.CancellationToken);

        Assert.Equal("https://dashboard.pangram.com/result/abc123", result.DashboardLink);
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    public async Task PredictAsync_NullOrEmptyText_ThrowsArgumentException(string? text)
    {
        using var client = ClientFactory.Create(ValidResponse);

        await Assert.ThrowsAsync<ArgumentException>(() =>
            client.PredictAsync(text!, cancellationToken: TestContext.Current.CancellationToken));
    }

    [Fact]
    public async Task PredictAsync_ApiReturns401_ThrowsPangramApiException()
    {
        using var client = ClientFactory.Create("Unauthorized", HttpStatusCode.Unauthorized);

        var ex = await Assert.ThrowsAsync<PangramApiException>(() =>
            client.PredictAsync("Hello", cancellationToken: TestContext.Current.CancellationToken));

        Assert.Equal(401, ex.StatusCode);
    }

    [Fact]
    public async Task PredictAsync_ApiReturnsErrorField_ThrowsPangramApiException()
    {
        using var client = ClientFactory.Create("""{"error": "invalid api key"}""");

        var ex = await Assert.ThrowsAsync<PangramApiException>(() =>
            client.PredictAsync("Hello", cancellationToken: TestContext.Current.CancellationToken));

        Assert.Contains("invalid api key", ex.Message);
    }
}